version: '3'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: server
    container_name: server
    ports:
      - "53:53"
    networks:
      dnsnet:
        ipv4_address: 192.1.1.2
  
  client1:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: client
    container_name: client1
    networks:
      dnsnet:
        ipv4_address: 192.1.1.3
    dns:
      - 192.1.1.2
  
  client2:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: client
    container_name: client2
    networks:
      dnsnet:
        ipv4_address: 192.1.1.4
    dns:
      - 192.1.1.2


networks:
  dnsnet:
    name: dnsnet
    driver: bridge
    # ip address:
    ipam:
      config:
        - subnet: "192.1.1.0/24"